Repository Smithsonian/SuperNOVAS, pull requests merged in 2025-09, with the labels that each got.

#222 Add CMake build tooling
  .github/workflows/build-cmake.yml
  .gitignore
  CMakeLists.txt
  Doxyfile
  README_CMAKE.md
  cmake/SuperNOVASConfig.cmake.in
  cmake/cmake_uninstall.cmake.in
  cmake/supernovas.pc.in
  examples/CMakeLists.txt
Labels: enhancement

#224 Simplify CMake CI
  .github/workflows/build-cmake.yml
Labels: enhancement

#226 Fix shared libs on Linux (no rpath!)
  Doxyfile.local
  Makefile
  build.mk
  config.mk
Labels: bug

#231 Non-UNIX builds / functionality
  CHANGELOG.md
  CMakeLists.txt
  Makefile
  examples/CMakeLists.txt
  src/docedit.c
  test/CMakeLists.txt
  test/src/test-calceph.c
  test/src/test-cio_file.c
  test/src/test-compat.c
  test/src/test-cspice.c
  test/src/test-errors.c
  test/src/test-super.c
Labels: enhancement

#232 Consolidate `novas_clock_skew()`
  CHANGELOG.md
  include/novas.h
  src/timescale.c
  test/src/test-errors.c
  test/src/test-super.c
Labels: enhancement

#233 Mean vs instantaneous clock skews
  CHANGELOG.md
  include/novas.h
  src/timescale.c
  test/src/test-errors.c
  test/src/test-super.c
Labels: enhancement

#236 Don't install CIO locator data
  CHANGELOG.md
  CMakeLists.txt
  Makefile
  README.md
  include/novas.h
  src/cio.c
  test/src/test-super.c
Labels: enhancement

#237 Install more documentation
  CHANGELOG.md
  CMakeLists.txt
  Doxyfile
  Makefile
Labels: enhancement

#238 Doxygen to use README.md as is.
  CHANGELOG.md
  Doxyfile
  LEGACY.md
  Makefile
  README.md
  resources/header.html
  src/docedit.c
Labels: enhancement

#239 Define catalog sources step-by-step
  .github/workflows/test.yml
  .settings/language.settings.xml
  CHANGELOG.md
  README.md
  examples/example-rise-set.c
  examples/example-star.c
  include/novas.h
  src/calendar.c
  src/frames.c
  src/parse.c
  src/spectral.c
  src/target.c
  src/timescale.c
  test/src/test-errors.c
  test/src/test-super.c
Labels: enhancement

#241 Overhaul document generation
  .github/workflows/dox.yml
  .gitignore
  CMakeLists.txt
  Makefile
  README.md
  benchmark/CMakeLists.txt
  doc/.gitignore
  doc/CMakeLists.txt
  doc/Doxyfile
  doc/Makefile
  doc/NOVAS-legacy.md
  doc/SuperNOVAS_vs_astropy.md
  doc/resources
  doc/src/docedit.c
  src/docedit.c
  test/CMakeLists.txt
Labels: enhancement

#246 Add `novas_itrf_transform_site()` and `novas_geodetic_transform_site()`
  CHANGELOG.md
  include/novas.h
  src/itrf.c
  src/observer.c
  test/src/test-errors.c
  test/src/test-super.c
Labels: enhancement

#248 Deprecate place() variants
  include/novas.h
  src/frames.c
  src/place.c
Labels: enhancement

#249 Option to exclude deprecated definitions from novas.h
  CHANGELOG.md
  README.md
  include/novas.h
  include/solarsystem.h
  src/equinox.c
  src/grav.c
  src/observer.c
  src/spectral.c
  src/util.c
Labels: documentation, enhancement

#252 Don't build legacy solsys going forward
  CHANGELOG.md
  CMakeLists.txt
  Makefile
  README.md
  config.mk
  include/solarsystem.h
  legacy/README.md
  legacy/cio_file.c
  legacy/eph_manager.c
  legacy/eph_manager.h
  legacy/readeph0.c
  legacy/solsys1.c
  legacy/solsys1.h
  legacy/solsys2.c
  legacy/solsys2.h
  src/place.c
  src/plugin.c
  src/solsys-calceph.c
  src/solsys-cspice.c
  src/solsys-ephem.c
  src/solsys3.c
  test/Makefile
  test/src/test-errors.c
Labels: enhancement

#253 Tweak build configs
  .github/workflows/build-cmake.yml
  .github/workflows/build.yml
  CHANGELOG.md
  CMakeLists.txt
  Makefile
  README.md
  build.mk
  config.mk
  examples/CMakeLists.txt
  examples/Makefile
  examples/example-cspice.c
  test/Makefile
Labels: enhancement

#255 Improved portability beyond UNIX (e.g. MSVC)
  .github/workflows/build-cmake.yml
  CHANGELOG.md
  CMakeLists.txt
  README.md
  benchmark/benchmark-nutation.c
  benchmark/benchmark-place.c
  examples/example-time.c
  include/novas.h
  src/frames.c
  src/parse.c
  src/refract.c
  src/target.c
  src/timescale.c
  src/util.c
  test/src/test-errors.c
  test/src/test-super.c
Labels: enhancement
